name: LsEnderChestConverter
version: 1.0.0
main: me.lopikss.lsenderchestconverter.LsEnderChestConverterPlugin
api-version: "1.21"

depend:
  - LsEnderChest

commands:
  lsecconvert:
    description: Convert vanilla Ender Chest contents into LsEnderChest storage
    usage: /lsecconvert <player|all>
    permission: lsec.convert

permissions:
  lsec.convert:
    description: Allows converting vanilla Ender Chests into LsEnderChest
    default: op